routes:
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /:
    data:
      post:
        resource: pages
        type: read
        slug: landing
    template:
      #- page
      - custom-home
  /posts/:
    controller: channel
    template: index
    #filter: tag:[podcast,dungeon-source]

collections:
  /announcements/:
    permalink: /announcements/{slug}/
    template: index
    filter: tag:announcements
  /gaming/:
    permalink: /gaming/{slug}/
    template: index
    filter: tag:gaming
  /osalt/:
    permalink: /osalt/{slug}/
    template: index
    filter: tag:osalt
  /squirrel-army/:
    permalink: /squirrel-army/{slug}/
    template: index
    filter: tag:squirrel-army
  /geeksabroad/:
    permalink: /geeksabroad/{slug}/
    template: index
    filter: tag:geeksabroad
  /podcast/:
    permalink: /podcast/{slug}/
    template: index
    filter: tag:podcast
  /events/:
    permalink: /events/{slug}/
    template: index
    filter: tag:events
  /dnd/:
    permalink: /dnd/{slug}/
    template: index
    filter: tag:dungeon-source
  /news/:
    permalink: /news/{slug}/
    template: index
    filter: tag:news
  /:
    permalink: /{slug}/
    template: index
    filter: tag:-[announcements,gaming,osalt,squirrel-army,geeksabroad,podcast,events,dungeon-source,news]


taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
